apiVersion: v1
kind: Pod
metadata:
  name: good-compliant-pod
  namespace: default
  labels:
    app: good-example
spec:
  containers:
    - name: nginx
      image: nginx
      resources:
        limits:
          cpu: "200m"
          memory: "256Mi"
        requests:
          cpu: "100m"
          memory: "128Mi"